### ISSUE TITLE
Add support for printing to stdout

### ISSUE THREAD

**Issue by liornoy** [openshift-kni/k8sreporter#7]
We should add the option to dump into stdout in case the "reportPath" param is empty in the constructor.

**Comment by fedepaol** [comment]
> We should add the option to dump into stdout in case the "reportPath" param is empty in the constructor.

Why we should? What would be the use case?
And in general, it'd be better to be explicit and have a parameter that enables stodout rather than relying on an implicit behaviour.

**Comment by liornoy** [comment]
that is because on an early version of the k8sreporter (before it had its own repo) it could
output into stdout, as the sriov uses it until today.
see: https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/1c6e1b3b1f6d70882d6245e5ccff4e9b70bf3948/test/conformance/test_suite_test.go#LL53C6-L53C6

**Comment by liornoy** [comment]
And I'm interested in upgrading sriov's reporter to this,
to align it as part of the cnf-split

**Comment by fedepaol** [comment]
I bet no one is using that mode, however it's fine, as long as we have an explicit parameter as I wrote above

**Comment by liornoy** [comment]
I discussed this with Sebastian and he agreed that we can omit this ability.
