### ISSUE TITLE
Make the Dump function more robust for special characters

### ISSUE THREAD

**Issue by liornoy** [openshift-kni/k8sreporter#8]
Found a case where the k8s reporter Dump was called on test case named: {"IPStack":"ipv4"} 
Later, on an HTML file-system app, the special characters such as { and " were invalid as part of the URL
and made the report unreachable. 

We should expand the `cleanDirName` function to catch all of the special characters that are invalid as
directory/file name and make it robust to any future example.

**Comment by fedepaol** [comment]
The fact that this becomes a reporter problem is debatable, even if it the quicker way to fix it
